### ISSUE TITLE
when I tokenize three datasets , There are 14029574132 tokens in the  pre train  corpus ,toal about 14T 

### ISSUE THREAD

**Issue by dshwei** [RUCKBReasoning/codes#11]
Dataset({
    features: ['input_ids', 'length'],
    num_rows: 975420
})
Dataset({
    features: ['input_ids', 'length'],
    num_rows: 1866910
})
Dataset({
    features: ['input_ids', 'length'],
    num_rows: 1026340
})
There are 14029574132 tokens in the corpus

in your paper you set " The training process uses a large batch size  comprising 4M tokens"
if model is 7b , max_sequence length is 8196,

as formul of per_device_train_batch_size   computed :
per_device_train_batch_size   =  40000000 / 8196 /8 / gradient_accumulation_steps 

so , what value of  per_device_train_batch_size  setted  and what  value of gradient_accumulation_steps  setted?
because 8*A800 , eigth gpus used , if gradient_accumulation_steps setting too much , will occuring OOM .

请问训练时 per_device_train_batch_size    和 gradient_accumulation_steps 分别设置多少？

**Comment by dshwei** [comment]
您好，看到pre-train dataset 预处理的时候，每个类型的数据集单独做了shuffle,但是三个数据集合并之后没有一起做shuffle，请问这样做对训练的结果有影响吗

**Comment by lihaoyang-ruc** [comment]
> Dataset({ features: ['input_ids', 'length'], num_rows: 975420 }) Dataset({ features: ['input_ids', 'length'], num_rows: 1866910 }) Dataset({ features: ['input_ids', 'length'], num_rows: 1026340 }) There are 14029574132 tokens in the corpus
> 
> in your paper you set " The training process uses a large batch size comprising 4M tokens" if model is 7b , max_sequence length is 8196,
> 
> as formul of per_device_train_batch_size computed : per_device_train_batch_size = 40000000 / 8196 /8 / gradient_accumulation_steps
> 
> so , what value of per_device_train_batch_size setted and what value of gradient_accumulation_steps setted? because 8*A800 , eigth gpus used , if gradient_accumulation_steps setting too much , will occuring OOM .
> 
> 请问训练时 per_device_train_batch_size 和 gradient_accumulation_steps 分别设置多少？

我们增量预训练时，一个global batch包含4M (million) tokens，因此请根据您的硬件条件动态调整per_device_train_batch_size和gradient_accumulation_steps的值，使得一个global batch包含4M (million) tokens就行。

**Comment by lihaoyang-ruc** [comment]
> 您好，看到pre-train dataset 预处理的时候，每个类型的数据集单独做了shuffle,但是三个数据集合并之后没有一起做shuffle，请问这样做对训练的结果有影响吗

我们在加载增量预训练数据的时候，一个batch内的sequences是随机采样来自三个数据集，因此并不存在三个数据集的训练先后问题，他们是被混合在一起训练的。
