### ISSUE TITLE
增量预训练的数据集中包含有starcoder 训练时使用的sql数据，这样重复使用slq数据进行训练，是否会出现遗忘其他问题

### ISSUE THREAD

**Issue by dshwei** [RUCKBReasoning/codes#12]
sql-related data：from the Stack v1.2  ， 共11G

**Comment by lihaoyang-ruc** [comment]
在CodeS中，因为我们的最终目标是增强starcoder在text-to-SQL任务上的能力，因此我们重复使用SQL数据的目的是来进一步增强starcoder在SQL上的能力。在这个过程中，我们并不需要starcoder保持其他与SQL不相关的能力（比如Python、C++，Java生成能力）。
