### ISSUE TITLE
codes-7b-bird 模型在本地测试bird dev 结果复现

### ISSUE THREAD

**Issue by dshwei** [RUCKBReasoning/codes#13]
您好，很感谢你的开源工作项目。
我下载您提供的codes-brid-7b (seeklhy/codes-7b-bird),在本地本地进行bird-dev 数据测试结果如下。和您在榜单上测试的dev的结果评分57.17 差了13个基点，
请问我本地的beid-dev测试和您榜单上的的得分在评估过程中有哪些不一样吗？
![image](https://github.com/RUCKBReasoning/codes/assets/42167236/905165c0-458c-4327-bb13-72dd5557efc4)

### 
simple               moderate             challenging          total               
count                925                  465                  144                  1534                
======================================
accuracy             53.73                29.89                29.17                44.20               
========================================================
Finished evaluation
starting to compare with knowledge for ves
start calculate
                     simple               moderate             challenging          total               
count                925                  465                  144                  1534                
=========================================
ves                  57.77                33.30                36.23                48.33               
========================================================

**Comment by lihaoyang-ruc** [comment]
重复issue
