### ISSUE TITLE
关于sql generate model 训练的细节

### ISSUE THREAD

**Issue by dshwei** [RUCKBReasoning/codes#15]
您好，关于sql generate model 的模型微调的一个细节问题想请教一下。
在sql generate  model 微调时，table schema 是使用的query SQL 中涉及到的表的所有column，
还是只使用了query SQL语句查询用到的colums ？
就是经过过滤，将整张表的所有columns进行过滤，只使用query SQL中select 用到的columns?

**Comment by lihaoyang-ruc** [comment]
训练时，我们会过滤出sql用到的tables和columns，同时也会保留一些不会用到的tables和columns，以提升模型的抗噪声能力。

**Comment by dshwei** [comment]
非常感谢您百忙之中的回复。
我有一个技术问题想请教一下，我首先是进行pretrain 增量训练，增量训练之后将模型进行保存，然后进行sft的微调。
上面两步执行是没有没有问题的，但是在sft之后保存的peft权重，和增量训练之后保存的模型进行merge合并的时候出现无法合并的问题。
增量训练和sft的脚本和启动脚本我都放在了附件中
我排查了很久也没有发现这个问题的原因，想请教一下这种情况是什么原因导致的


非常感谢您的不吝赐教
