### ISSUE TITLE
双向数据增强技术请教

### ISSUE THREAD

**Issue by mojianpo** [RUCKBReasoning/codes#16]
咱们论文中提到的： we propose a bi-directional data augmentation technique to automatically generate a large set of authentic and general (question, SQL) pairs with minimal annotation costs.
这个双向数据增强技术，自动化生成 QA 对，这个技术方案或者示例代码，烦请给提供下，多谢。
目前在学习研究这块： 基于DDL  自动生成各种范式的SQL语料（问题，SQL）.

多谢。

**Comment by lihaoyang-ruc** [comment]
已更新，请查看DomainAdaptation文件夹。
