### ISSUE TITLE
您的实验中增量预训练选择starcoder基模型，如果选择code llama2-7b基模型，请问有做过实验对比吗？

### ISSUE THREAD

**Issue by dshwei** [RUCKBReasoning/codes#17]
text2SQL ,我选择code llama2 -7b 先做增量预训练，然后SFT的效果还不如直接选择code llama2-7b 做SFT的模型效果.请问您有没有做过这方面的实验？

**Comment by dshwei** [comment]
请问在做完增量预训练之后有没有对模型进行评估？
在HumanEval和 MBPP benchmark 上

**Comment by lihaoyang-ruc** [comment]
> text2SQL ,我选择code llama2 -7b 先做增量预训练，然后SFT的效果还不如直接选择code llama2-7b 做SFT的模型效果.请问您有没有做过这方面的实验？

我们没有在code llama上进行过增量预训练，但我后来在llama2和deepseek-coder上都做过增量预训练，发现llama2的效果提升比较明显，但是deepseek-coder效果提升不太明显（大概1-2个点的提升）。我认为这可能与基座模型本身的text2sql能力有关。llama2本身能力太差，因此加了增量预训练之后text2sql能力提升的很多；但是deepseek-coder本身text2sql能力就极强，这时候可能增量预训练带来的性能收益并不高。

**Comment by lihaoyang-ruc** [comment]
> 请问在做完增量预训练之后有没有对模型进行评估？ 在HumanEval和 MBPP benchmark 上

我们不需要CodeS在除了text2sql之外的其他任务上通用，因此没有在HumanEval和 MBPP benchmark上进行评估。

**Comment by dshwei** [comment]
非常感谢您的不吝赐教。
有一个开源项目DTS-SQL不知道您是否复现过这个项目。我在复现这个项目时，schema linker 模型我可以做到更高的精度和召回。
Total Accuracy: 0.6949152542372882
Filtered Accuracy: 0.7940026075619296
Average Precision: 0.9176879617557584
Average Recall: 0.9058018252933516


但是 sql&nbsp; generate model 我始终复现不出来。
即使我的单独的sql generate model 效果要比作者开源的模型还要好(只是用sql generate&nbsp; 单一模型进行推理，不使用schema linker, 且推理的时候使用数据库中全部的table schemas).


但是在使用schema linker + sql generate pipeline 的方式进行推理的时候，效果就和开源作者的相差很多。
作者的模型准确率可以达到0.55，我的只能达到0.43 相差很大。

请问您有没有复现DTS-sql的效果。
相关的github 链接：
MohammadrezaPourreza/DTS-SQL: This repository contains all the code for the DTS-SQL paper (github.com)

模型权重链接：
Schema linker:&nbsp;https://huggingface.co/MrezaPRZ/DeepSchema_BIRD
SQL generator:&nbsp;https://huggingface.co/MrezaPRZ/DeepSQL_BIRD

祝好
