### ISSUE TITLE
数据集相关问题

### ISSUE THREAD

**Issue by steph730** [RUCKBReasoning/codes#3]
请问数据集中table_label，columnb_label，matched_contents这几个内容是怎么获取到的呢

**Comment by lihaoyang-ruc** [comment]
table_label和columnb_label可以直接从数据集标注好的SQL中抽取出来。matched_contents则稍微复杂，它根据问题和数据库内容的字符串重合度进行匹配，从而抽取出问题可能涉及的数据库内容，以帮助模型生成SQL中的WHERE条件。

这些数据预处理代码同样会在不久后放出，感谢关注。

**Comment by steph730** [comment]
> table_label和columnb_label可以直接从数据集标注好的SQL中抽取出来。matched_contents则稍微复杂，它根据问题和数据库内容的字符串重合度进行匹配，从而抽取出问题可能涉及的数据库内容，以帮助模型生成SQL中的WHERE条件。
> 
> 这些数据预处理代码同样会在不久后放出，感谢关注。

好的谢谢！再请问一下，我在few shot方法使用sentence-transformers对问题和问题skeleton进行embeddings生成，用faiss进行相似度比对，最终准确率0.36，与项目中的效果差了9个点，simcse+roberta会比sentence transformer好这么多嘛

**Comment by lihaoyang-ruc** [comment]
请问roberta指的是schema item classifier吗？

**Comment by steph730** [comment]
> 请问roberta指的是schema item classifier吗？

没有没有，就是simcse里使用的模型，我看里边用的是roberta

**Comment by lihaoyang-ruc** [comment]
如果只是换了一个demonstration retriever就掉9%的性能有点奇怪。

我之前在Codes-15B上做过消融实验，如果不采用我们的retriever，而是随机从训练集中抽取若干样例拼到上下文作为demonstrations，那么它在bird上的few shot性能将会掉2个点或者更多。

**Comment by steph730** [comment]
> 如果只是换了一个demonstration retriever就掉9%的性能有点奇怪。
> 
> 我之前在Codes-15B上做过消融实验，如果不采用我们的retriever，而是随机从训练集中抽取若干样例拼到上下文作为demonstrations，那么它在bird上的few shot性能将会掉2个点或者更多。

好的谢谢，我再看看有没有别的问题，不过效果已经很好了
