### ISSUE TITLE
Tokenize error

### ISSUE THREAD

**Issue by Kaimary** [RUCKBReasoning/codes#6]
When I executed the tokenize_pt_corpus.py script to tokenize the corpus, it encountered an error,
<img width="1510" alt="Screenshot 2024-04-06 at 16 40 28" src="https://github.com/RUCKBReasoning/codes/assets/12944968/7b266eeb-1b1a-4989-9d24-dd9be79964c5">

**Comment by lihaoyang-ruc** [comment]
This error likely occurred due to insufficient memory available during the execution of tokenize_pt_corpus.py.

**Comment by Kaimary** [comment]
Thanks. I solved the problem finally.
