### ISSUE TITLE
模型微调

### ISSUE THREAD

**Issue by shellhuang1227** [RUCKBReasoning/codes#8]
你好，请问模型支持微调吗？想用一些数据微调codes15b，微调代码工程使用LLaMA-Factory，然后用微调后的模型再在spider和bird上进行推理，看效果相比codes15b会怎样变化。如果可以的话，可以提示下需要注意的地方吗（比如数据、模板等）？

**Comment by lihaoyang-ruc** [comment]
base模型是支持微调的（codes-1b, codes-3b, codes-7b, 和codes-15b），我们也开放了微调脚本[train_causal_lm.py](https://github.com/RUCKBReasoning/codes/blob/main/train_causal_lm.py)，并在README里写了如何微调。如果你使用LLaMA-Factory进行微调的话，你需要提前将数据处理成<instruction, input, output>三元组，其中input可以是空的，instruction包括database prompt和question，详见[load_sft_dataset.py](https://github.com/RUCKBReasoning/codes/blob/main/utils/load_sft_dataset.py)文件。模版只需要保证训练和评估时一致就行。

**Comment by shellhuang1227** [comment]
好的，感谢。
1、因为我打算用这个数据（https://huggingface.co/datasets/Healthy13/Text2SQL ）进行微调，数据格式就是<instruction, input, output>三元组，所以使用LLaMA-Factory进行微调的话不用进行数据处理了。而如果用您项目里的微调脚本，是需要已知数据的databases和tables等信息，然后把数据处理成sft_spider_train_text2sql.json类似的格式对吗？而我打算用的这个数据是没有这些信息的，所以我不太清楚如何使用您项目中的微调脚本？
2、此外，我如果用这个模板进行微调训练，那在spider推理时，也需要在text2sql_few_shot.py推理代码中修改input为这个输入吗？_register_template(
    name="default",
    format_user=StringFormatter(slots=["Human: {{content}}\nAssistant: "]),
    format_system=StringFormatter(slots=["{{content}}\n"]),
    format_separator=EmptyFormatter(slots=["\n"]),
)

**Comment by lihaoyang-ruc** [comment]
1. 是的，如果想用CodeS中提出的database prompt construction方案，就需要把数据处理成sft_spider_train_text2sql.json一样的格式。
2. 如果用这个模版进行微调，推理时需要让text2sql_zero_shot.py（不是text2sql_few_shot.py，这个是few-shot脚本）的输入格式修改成一样。不过我建议您使用LLaMA-Factory自带的推理脚本进行推理，这样就不用考虑格式对齐的问题了。

**Comment by shellhuang1227** [comment]
好的，明白了。
我基于LLaMA-Factory和default模板用上述数据集的200多条数据对codes-15b进行了微调，然后基于微调后的模型使用LLaMA-Factory的推理脚本在spider-dev上进行了推理，而后的评估结果是27.9分。请问准确率这么低会是因为微调数据量比较少吗？但是codes-15b基础模型在few-shot情况下spider上的准确率挺高的呢。

**Comment by lihaoyang-ruc** [comment]
上述数据集的质量好像是挺低的。。。你可以尝试直接使用spider的训练集进行微调，然后在spider的dev集上进行测试。

**Comment by shellhuang1227** [comment]
好的，我试一下，感谢~
麻烦再问个问题，您有试过codes-7b-spider微调模型在bird上的推理效果怎么样嘛？针对某个数据集的train集微调，在相应数据集的dev集上可以取得较好效果，但是在其他数据集上效果怎么样呢？

**Comment by lihaoyang-ruc** [comment]
> 您有试过codes-7b-spider微调模型在bird上的推理效果怎么样嘛？

这个没有尝试过，因为spider和bird的标注习惯以及难度不同（其实就是它们的数据分布不同），而codes-7b-spider已经完全拟合了spider的数据分布，因此在bird上可能效果并不是很好。我后来把spider和bird这些训练数据合并到一起，训练了一个7b的模型，名为codes-7b-merged，这个模型可以在spider和bird上都有不错的效果。

> 针对某个数据集的train集微调，在相应数据集的dev集上可以取得较好效果，但是在其他数据集上效果怎么样呢？

spider和bird都是cross-domain能力的评估，也就是说训练时见到的数据库schema和测试时没有重合。

**Comment by shellhuang1227** [comment]
好，我明白啦，非常感谢！
