### ISSUE TITLE
Is it possible to upload basic models to Alibaba’s modelscope platform to facilitate downloading by domestic users?

### ISSUE THREAD

**Issue by CycloneBoy** [RUCKBReasoning/codes#9]
You guys are doing a great job and it's very useful. Given that huggingface is not very easy to access domestically, it would be a great help to the community if you guys could also upload a copy of the base model to the domestic platform.

For example, the [modelscope](https://modelscope.cn) site.

**Comment by lihaoyang-ruc** [comment]
We plan to upload the models to Quark Cloud Disk within the next two days. Thank you for your valuable suggestions.

**Comment by CycloneBoy** [comment]
That would be very helpful, thank you very. 👍👍👍

**Comment by CycloneBoy** [comment]
That would be very helpful, thank you very much.

**Comment by lihaoyang-ruc** [comment]
Hello! I hope you are all doing well. We have uploaded the base models to Quark Cloud Disk. Here are the links:

[codes-15b.zip](https://pan.quark.cn/s/857dd3f22a47) (pwd: deHP)
[codes-7b.zip](https://pan.quark.cn/s/faecf02e81d6) (pwd: iNk3)
[codes-3b.zip](https://pan.quark.cn/s/da6338c944ea) (pwd: BvP6)
[codes-1b.zip](https://pan.quark.cn/s/1ed02ef576e3) (pwd: 2xzD)
